name: Deploy-chaby
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: file-converter-runner
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_TIMEWEB_SWEATCLUB_ID_RSA_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/pttrulez-subdomains/file-converter
            git pull
            npm install
            npm run compile
            pm2 restart file-converter
